import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
import { Fira_Sans } from "next/font/google";

// Load fonts
const firaSans = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Example weights
  variable: '--font-fira-sans',
});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaSans.variable}`}>
        <div>
          {/* Main Navigation */}
          <Navigation />

          {/* Main Content */}
          <main>{children}</main>

          {/* Footer (Optional) */}
          {/* <footer
            style={{
              padding: "1rem",
              textAlign: "center",
              backgroundColor: "#333",
              color: "white",
            }}
          >
            <p>
              © {new Date().getFullYear()} Your Company. All rights reserved.
            </p>
          </footer> */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
